import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import fs from 'node:fs';
import App from './App';

vi.mock('./Select', () => ({ Select: ({ label, value, options, onChange, disabled }: { label: string; value: string; options: {value: string; label: string}[]; onChange:(value:string)=>void; disabled?:boolean }) => <select aria-label={label} value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select> }));
const manifest = JSON.parse(fs.readFileSync('public/dashboard/manifest.json','utf8'));
const supplemental = JSON.parse(fs.readFileSync('public/dashboard/supplemental.json','utf8'));
beforeEach(() => {
  vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => ({ok:true,json:async()=>url.includes('supplemental')?supplemental:manifest})));
  vi.stubGlobal('matchMedia',()=>({matches:true,addEventListener:vi.fn(),removeEventListener:vi.fn()}));
  vi.stubGlobal('scrollTo',vi.fn());
  window.history.replaceState({},'', '/?page=overview&quarter=3&group=both&role=all');
});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
describe('Интеграция обращений и ФОТ',()=>{
  it('обращения по умолчанию сравнивают август с июлем без квартальных кнопок',async()=>{
    render(<App/>);
    const card = await screen.findByRole('article',{name:'Обращения клиентов'});
    const pilotDelta = await within(card).findByLabelText('-3,7% к июлю');
    expect(pilotDelta.textContent).toBe('-3,7%');
    expect(pilotDelta.classList.contains('sales-delta')).toBe(true);
    expect(pilotDelta.classList.contains('down')).toBe(true);
    expect(within(card).getByLabelText('-7,8% к июлю')).toBeTruthy();
    expect(within(card).getByText(/12\s442/).classList.contains('sales-number')).toBe(true);
    expect(within(card).getByText(/18\s266/).classList.contains('sales-number')).toBe(true);
    expect(within(card).queryByRole('group',{name:'Квартальная динамика — выберите квартал'})).toBeNull();
    expect(within(within(card).getByRole('group',{name:'Период обращений'})).getByRole('button',{name:'Август'}).getAttribute('aria-pressed')).toBe('true');
    expect(within(within(card).getByRole('group',{name:'Сравнить с'})).getByRole('button',{name:'Июль'}).getAttribute('aria-pressed')).toBe('true');
    expect(within(card).queryByText('2 месяца против 3 · фактические суммы')).toBeNull();
    expect(within(card).queryByText('Периоды несопоставимы')).toBeNull();
  });
  it('предыдущий месяц следует за периодом; произвольная база сохраняется и восстанавливается одной кнопкой',async()=>{
    render(<App/>);
    const card = await screen.findByRole('article',{name:'Обращения клиентов'});
    const periods = await within(card).findByRole('group',{name:'Период обращений'});
    fireEvent.click(within(periods).getByRole('button',{name:'Июль'}));
    const base = within(card).getByRole('group',{name:'Сравнить с'});
    const selectedBase = () => within(base).getByRole('button',{pressed:true}).getAttribute('aria-label');
    expect(selectedBase()).toBe('Июнь');
    expect(new URLSearchParams(window.location.search).get('appealBaseMonth')).toBe('6');
    fireEvent.click(within(base).getByRole('button',{name:'Февраль'}));
    fireEvent.click(within(within(card).getByRole('group',{name:'Период обращений'})).getByRole('button',{name:'Август'}));
    expect(selectedBase()).toBe('Февраль');
    fireEvent.click(within(card).getByRole('button',{name:'К предыдущему'}));
    expect(selectedBase()).toBe('Июль');
    fireEvent.click(within(periods).getByRole('button',{name:'Январь'}));
    expect(selectedBase()).toBe('Июль');
    expect(new URLSearchParams(window.location.search).get('appealMonth')).toBe('1');
    expect(new URLSearchParams(window.location.search).get('quarter')).toBe('3');
  });
  it('нижняя полоска показывает число базы, сохраняя число основного месяца',async()=>{
    window.history.replaceState({},'', '/?page=overview&quarter=3&group=both&role=all&appealMonth=1&appealBaseMonth=7');
    render(<App/>);
    const card = await screen.findByRole('article',{name:'Обращения клиентов'});
    const comparison = await within(card).findByRole('group',{name:'Сравнить с'});
    expect(within(card).getByText(/13\s373/)).toBeTruthy();
    expect(within(card).getByText(/18\s193/)).toBeTruthy();
    expect(within(within(card).getByRole('group',{name:'ТБ с пилотом: база сравнения, Июль'})).getByText(/12\s916/)).toBeTruthy();
    expect(within(card).getByLabelText('+3,5% к июлю')).toBeTruthy();
    fireEvent.click(within(comparison).getByRole('button',{name:'Август'}));
    expect(within(card).getByText(/13\s373/)).toBeTruthy();
    expect(within(card).getByText(/18\s193/)).toBeTruthy();
    expect(within(within(card).getByRole('group',{name:'ТБ с пилотом: база сравнения, Август'})).getByText(/12\s442/)).toBeTruthy();
    expect(within(within(card).getByRole('group',{name:'Остальные ТБ: база сравнения, Август'})).getByText(/18\s266/)).toBeTruthy();
    expect(within(card).getByLabelText('+7,5% к августу')).toBeTruthy();
  });
  it.each([1, 2, 3])('получатели показывают июль к марту при выбранном квартале %s, объём тоже сравнивает месяцы',async(quarter)=>{
    window.history.replaceState({}, '', `/?page=overview&quarter=${quarter}&group=both&role=all`);
    render(<App/>);
    const card = await screen.findByRole('article',{name:'ФОТ и получатели'});
    await within(card).findByLabelText('+13,7% к марту');
    fireEvent.click(within(card).getByRole('button',{name:'Получатели, шт.'}));
    expect(within(card).getAllByText(/652\s053/).length).toBeGreaterThan(0);
    expect(within(card).getByLabelText('-5,2% к марту').classList.contains('sales-delta')).toBe(true);
    expect(within(card).getByLabelText('-6% к марту')).toBeTruthy();
    expect(within(card).getAllByText('Июль')).toHaveLength(3);
    expect(within(card).getByText(/687\s563/)).toBeTruthy();
    expect(within(card).getByText(/9\s649\s777/)).toBeTruthy();
    expect(within(card).getByLabelText('-5,2% к марту').classList.contains('sales-number')).toBe(true);
    expect(within(card).getByText(/652\s053/).classList.contains('sales-number')).toBe(false);
    expect(within(card).queryByRole('group',{name:'Квартальная динамика — выберите квартал'})).toBeNull();
    expect(card.textContent).not.toContain('Нет данных за II квартал');
    const chart = within(card).getByRole('region', {name:'Абсолютное изменение с марта'});
    expect(within(chart).getByText(/−35\s510 чел\./)).toBeTruthy();
    expect(within(chart).getByText(/−581\s062 чел\./)).toBeTruthy();
    expect(within(card).getAllByText(/652\s053/)).toHaveLength(1);
    expect(new URLSearchParams(window.location.search).get('quarter')).toBe(String(quarter));
    fireEvent.click(within(card).getByRole('button',{name:'Объём, ₽'}));
    expect(within(card).getByLabelText('+13,7% к марту')).toBeTruthy();
    expect(within(card).getByLabelText('+15,4% к марту')).toBeTruthy();
    expect(within(card).queryByRole('group',{name:'Квартальная динамика — выберите квартал'})).toBeNull();
    fireEvent.click(within(card).getByRole('button',{name:'Получатели, шт.'}));
    fireEvent.click(within(card).getByRole('link',{name:'Открыть анализ: ФОТ и получатели'}));
    expect(await screen.findByRole('heading',{level:1,name:'Анализ'})).toBeTruthy();
    expect(screen.getByRole('columnheader',{name:'Март'})).toBeTruthy();
    expect(screen.getByRole('columnheader',{name:'Июль'})).toBeTruthy();
    expect(screen.getByRole('columnheader',{name:'Изменение, %'})).toBeTruthy();
    expect(screen.queryByRole('group',{name:'Квартальная динамика — выберите квартал'})).toBeNull();
    expect(screen.queryByText('Для получателей без соседнего квартального среза процент не рассчитывается.')).toBeNull();
  });
  it('месяцы обращений меняют суммы, проценты и рейтинг, сохраняя ФОТ и ссылку на анализ',async()=>{
    render(<App/>);
    const card = await screen.findByRole('article',{name:'Обращения клиентов'});
    const periods = await within(card).findByRole('group',{name:'Период обращений'});
    const period = within(periods).getByRole('button',{name:'Март'});
    fireEvent.click(period);
    fireEvent.click(within(within(card).getByRole('group',{name:'Сравнить с'})).getByRole('button',{name:'Январь'}));
    expect(within(card).getByLabelText('+33,1% к январю')).toBeTruthy();
    expect(within(card).getByText(/17\s799/)).toBeTruthy();
    expect(card.querySelector('.fikri-ranking-row')?.textContent).toMatch(/Юго-Западный6\s298/);
    expect(card.querySelector('.supplemental-notes')).toBeNull();
    expect(within(card).queryByText('Источник и ограничения')).toBeNull();
    expect(new URLSearchParams(window.location.search).get('quarter')).toBe('3');
    expect(new URLSearchParams(window.location.search).get('appealMonth')).toBe('3');
    expect(new URLSearchParams(window.location.search).get('appealBaseMonth')).toBe('1');
    const payroll = screen.getByRole('article',{name:'ФОТ и получатели'});
    expect(payroll.querySelector('.supplemental-quarters small')).toBeNull();
    expect(payroll.querySelector('.supplemental-notes')).toBeNull();
    expect(within(payroll).queryByText('Источник и ограничения')).toBeNull();
    expect(within(payroll).getByLabelText('+13,7% к марту')).toBeTruthy();
    expect(within(card).getByLabelText('+33,1% к январю')).toBeTruthy();
    fireEvent.click(within(card).getByRole('link',{name:'Открыть анализ: Обращения клиентов'}));
    expect(await screen.findByRole('columnheader',{name:'Январь'})).toBeTruthy();
    expect(screen.getByRole('columnheader',{name:'Март'})).toBeTruthy();
    expect(screen.getByRole('columnheader',{name:'Изменение, %'})).toBeTruthy();
    expect(screen.queryByRole('article', {name:'Обращения клиентов'})).toBeNull();
    fireEvent.click(within(screen.getByRole('group',{name:'Сравнить с'})).getByRole('button',{name:'Март'}));
    expect(within(screen.getByRole('table')).getAllByText('0%').length).toBeGreaterThan(0);
  });
  it('ФОТ использует крупные цифры и короткие подписи, сохраняя пояснения в анализе',async()=>{
    render(<App/>);
    const card = await screen.findByRole('article',{name:'ФОТ и получатели'});
    await within(card).findByLabelText('+13,7% к марту');
    expect(card.querySelectorAll('.supplemental-totals .sales-number')).toHaveLength(2);
    expect(card.querySelector('.supplemental-totals .sales-group')?.textContent).toBe('Пилот');
    expect(card.querySelector('.supplemental-totals .sales-number')?.textContent).toBe('+13,7%');
    expect(within(card).getByText('48,2 млрд ₽')).toBeTruthy();
    expect(within(card).getByText('42,4 млрд ₽')).toBeTruthy();
    expect(within(card).getByText('655,5 млрд ₽')).toBeTruthy();
    expect(within(card).getByLabelText('+15,4% к марту').classList.contains('sales-number')).toBe(true);
    expect(card.querySelector('.supplemental-quality')).toBeNull();
    expect(card.querySelector('.supplemental-totals small')).toBeNull();
    expect(card.querySelector('.fikri-waterfall')).toBeNull();
    expect(within(card).getByLabelText('+13,7% к марту')).toBeTruthy();
    expect(within(card).getByLabelText('+15,4% к марту')).toBeTruthy();
    expect(card.textContent).not.toContain('Без привязки');
    const chart = within(card).getByRole('region', {name:'Абсолютное изменение с марта'});
    expect(within(chart).getByText('+5,8 млрд ₽')).toBeTruthy();
    expect(within(chart).getByText('+100,7 млрд ₽')).toBeTruthy();
    expect(within(card).getAllByText('756,2', {exact:false})).toHaveLength(1);
    expect(chart.textContent).not.toContain('48,2');
    fireEvent.click(within(card).getByRole('link',{name:'Открыть анализ: ФОТ и получатели'}));
    expect(await screen.findByText('Источники и правила', {selector:'summary'})).toBeTruthy();
    expect(screen.getByRole('columnheader',{name:'Март'})).toBeTruthy();
    expect(screen.getByRole('columnheader',{name:'Июль'})).toBeTruthy();
    expect(screen.getByRole('columnheader',{name:'Изменение, %'})).toBeTruthy();
    expect(screen.queryByRole('columnheader',{name:/квартал/})).toBeNull();
    expect(screen.queryByRole('article', {name:'ФОТ и получатели'})).toBeNull();
    expect(screen.getByText(/Остальные клиенты, включая записи без определённого сотрудника/)).toBeTruthy();
    expect(screen.queryByRole('link',{name:'Fikri · Conversions / Bubble Chart'})).toBeNull();
  });
  it('прямая ссылка на обращения открывает ТБ-таблицу с неактивными ролевым и продуктовым фильтрами',async()=>{
    window.history.replaceState({},'','/?page=analysis&metric=appeals&quarter=2');
    render(<App/>);
    await screen.findByRole('table');
    expect(screen.queryByRole('combobox',{name:'Продукты'})).toBeNull();
    expect(screen.queryByRole('combobox',{name:'Роль пилота'})).toBeNull();
    expect(screen.getByText('Тербанк / группа')).toBeTruthy();
    expect(screen.getByText('Источники и правила', {selector:'summary'})).toBeTruthy();
    expect(screen.getByText('Тербанки целиком')).toBeTruthy();
    expect(screen.queryByRole('article', {name:'Обращения клиентов'})).toBeNull();
    expect(screen.getByRole('columnheader',{name:'Август'})).toBeTruthy();
    expect(screen.getByRole('columnheader',{name:'Июль'})).toBeTruthy();
    fireEvent.change(screen.getByRole('combobox',{name:'Показатель'}),{target:{value:'sales'}});
    await waitFor(()=>expect(screen.queryByText('Тербанк / группа')).toBeNull());
  });
  it('ошибка загрузки новых источников не ломает остальные карточки; повторная загрузка работает',async()=>{
    const fetcher = vi.mocked(fetch);
    fetcher.mockImplementation(async input=>({ok:!String(input).includes('supplemental'),json:async()=>manifest}) as Response);
    render(<App/>);
    expect(await screen.findByRole('article',{name:'Удовлетворённость'})).toBeTruthy();
    const retries = await screen.findAllByRole('button',{name:'Повторить загрузку'});
    fetcher.mockImplementation(async input=>({ok:true,json:async()=>String(input).includes('supplemental')?supplemental:manifest}) as Response);
    fireEvent.click(retries[0]);
    await screen.findByText(/12\s442/);
    expect(screen.queryByText('Не удалось загрузить обращения и ФОТ. Проверьте доступность источников.')).toBeNull();
  });
});
